"""
Report generator — final node in the pipeline.

Synthesizes outputs from all upstream agents into a clean, readable report.
The report is what the Streamlit UI actually displays.

Two entry points:
  run()            — standard diagnostic report
  run_emergency()  — short-form emergency triage report (skips full treatment planning)
"""

from __future__ import annotations

import anthropic

_client = anthropic.Anthropic()

REPORT_SYSTEM = """You are a medical report writer. Your job is to synthesize multiple specialist
analyses into a clear, organized clinical summary that a patient (or their doctor) can read.

Structure the report with these sections, using markdown headers:

## Patient Summary
Demographics and chief complaint.

## Symptom Assessment
Key findings from symptom analysis, severity level.

## Diagnosis
Primary diagnosis with confidence level. Top differential diagnoses.

## Treatment Plan
Recommended interventions, medications with doses, lifestyle changes.

## Drug Interactions
Any interaction warnings found during treatment planning.

## Follow-Up & Monitoring
When to follow up, what symptoms should trigger immediate return.

## Important Disclaimers
Always end with: This report was generated by an AI diagnostic assistant for
educational purposes. It does not constitute medical advice. Please consult
a qualified healthcare provider for diagnosis and treatment."""

EMERGENCY_SYSTEM = """You are a medical triage specialist. Generate a SHORT emergency triage report.

Structure:
## EMERGENCY ALERT
State the likely emergency condition clearly.

## Immediate Actions Required
Bullet list of what the patient must do RIGHT NOW (call 911, go to ER, etc.)

## Do NOT
What not to do while waiting for emergency care.

## Symptoms Reported
Brief summary.

---
This is an emergency alert generated by an AI system. CALL EMERGENCY SERVICES IMMEDIATELY."""


class ReportGenerator:

    def run(self, state: dict) -> dict:
        age = state.get("age", "unknown")
        gender = state.get("gender", "unknown")
        symptoms = state.get("symptoms", [])
        symptom_description = state.get("symptom_description", "")
        symptom_analysis = state.get("symptom_analysis", "")
        severity = state.get("severity_level", "medium")
        diagnosis = state.get("diagnosis", "")
        differentials = state.get("differential_diagnoses", [])
        treatment_plan = state.get("treatment_plan", "")
        drug_interactions = state.get("drug_interactions", "")

        user_message = (
            f"Patient: {age}-year-old {gender}\n"
            f"Chief Complaint: {', '.join(symptoms)} — {symptom_description}\n"
            f"Severity: {severity}\n\n"
            f"=== SYMPTOM ANALYSIS ===\n{symptom_analysis}\n\n"
            f"=== DIAGNOSIS ===\n{diagnosis}\n\n"
            f"=== TREATMENT PLAN ===\n{treatment_plan}\n\n"
            f"=== DRUG INTERACTIONS ===\n{drug_interactions}\n\n"
            "Generate a comprehensive, readable clinical report."
        )

        response = _client.messages.create(
            model="claude-sonnet-4-6",
            max_tokens=4000,
            system=REPORT_SYSTEM,
            messages=[{"role": "user", "content": user_message}],
        )

        report = _extract_text(response)

        return {
            "final_report": report,
            "messages": [{"role": "report_generator", "content": report}],
        }

    def run_emergency(self, state: dict) -> dict:
        symptoms = state.get("symptoms", [])
        description = state.get("symptom_description", "")
        analysis = state.get("symptom_analysis", "")
        age = state.get("age", "unknown")

        user_message = (
            f"Patient age: {age}\n"
            f"Symptoms: {', '.join(symptoms)}\n"
            f"Description: {description}\n"
            f"Symptom Analysis: {analysis}\n\n"
            "Generate an emergency triage report immediately."
        )

        response = _client.messages.create(
            model="claude-sonnet-4-6",
            max_tokens=1500,
            system=EMERGENCY_SYSTEM,
            messages=[{"role": "user", "content": user_message}],
        )

        report = _extract_text(response)

        return {
            "final_report": report,
            "messages": [{"role": "emergency_report", "content": report}],
        }


def _extract_text(response) -> str:
    for block in response.content:
        if hasattr(block, "text"):
            return block.text
    return ""
